prefix = "."
stop-words = "stopwords.txt"

dataset = "data"
corpus = "line.toml"
index = "idx"

query-judgements = "data/queryrelevance.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "data/movie_sample_queries.txt"
query-id-start = 1
